apiVersion: v1
kind: Service
metadata:
  namespace: ns-elk
  name: elasticsearch-master
  labels:
    app: elasticsearch
    role: master
spec:
  clusterIP: None
  selector:
    app: elasticsearch
    role: master
  ports:
    - port: 9200
      name: http
    - port: 9300
      name: node-to-node
---
apiVersion: v1
kind: Service
metadata:
  namespace: ns-elk
  name: elasticsearch-data
  labels:
    app: elasticsearch
    role: data
spec:
  clusterIP: None
  selector:
    app: elasticsearch
    role: data
  ports:
    - port: 9200
      name: http
    - port: 9300
      name: node-to-node
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-address-type: "intranet"
    # alicloud-loadbalancer-id 更改为对应阿里云 SLB ID 
    service.beta.kubernetes.io/alicloud-loadbalancer-id: "lb-wz96ujq51shspyxb5hpd7"
    service.beta.kubernetes.io/alicloud-loadbalancer-force-override-listeners: "true"
  namespace: ns-elk
  name: elasticsearch-service
  labels:
    app: elasticsearch
    role: client
spec:
  externalTrafficPolicy: Local
  sessionAffinity: None
  type: LoadBalancer
  ports:
    - port: 9200
      targetPort: 9200
  selector:
    app: elasticsearch
    role: client
