apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
  namespace: ns-elk
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
  logstash.conf: |
    # 参考：https://www.elastic.co/guide/en/logstash/current/plugins-inputs-kafka.html
    input {
      kafka {
        bootstrap_servers => "kafka.ns-elk.svc.cluster.local:9092"
        topics => ["filebeat"]
        # 保留容器日志的 json 格式
        codec => "json"
      }
    }
    filter {
      date {
        match => [ "timestamp" , "dd/MMM/yyyy:HH:mm:ss Z" ]
      }
    }
      # 参考：https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html
      output {
        elasticsearch {
          hosts => ["elasticsearch-service:9200"]
          user => "elastic"
          password => "03sWFWzGOjNOCioqcbV3"
          # 参考：https://discuss.elastic.co/t/separate-indexes-for-each-kubernetes-namespace/169131/3
          # 根据 kubernetes.pod.name 字段单独创建 pod 的索引
          index => "%{[kubernetes][pod][name]}-%{+YYYY.MM.dd}"
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash-deployment
  namespace: ns-elk
spec:
  selector:
    matchLabels:
      app: logstash
  replicas: 3
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:7.14.0
        ports:
        - containerPort: 5044
        volumeMounts:
          - name: config-volume
            mountPath: /usr/share/logstash/config
          - name: logstash-pipeline-volume
            mountPath: /usr/share/logstash/pipeline
          - mountPath: /etc/localtime
            name: localtime
      volumes:
      - name: config-volume
        configMap:
          name: logstash-configmap
          items:
            - key: logstash.yml
              path: logstash.yml
      - name: logstash-pipeline-volume
        configMap:
          name: logstash-configmap
          items:
            - key: logstash.conf
              path: logstash.conf
      - hostPath:
          path: /etc/localtime
        name: localtime
---
kind: Service
apiVersion: v1
metadata:
  name: logstash-service
  namespace: ns-elk
spec:
  selector:
    app: logstash
  ports:
  - protocol: TCP
    port: 5044
    targetPort: 5044